### ISSUE TITLE
How to work with Farsi Calender datepicker

### ISSUE THREAD

**Issue by zohanve** [euwars/iOSCourse#1]
سلام. من خیلی تازه وارد هستم و تاحالا تو محیط گیت هاب کار نکردم. 
من یه برنامه ای دارم مینویسم که باید از کاربر تاریخ جلالی رو بگیره و اون تاریخ را به عنوان متغیر اینتجر در نظر بگیره که بتونه روش عملیات ریاضی(مثل جمع و ضرب و کوچکترمساوی و ..) انجام بده.
و الان مشکلی که هست اینه که زمانیکه تاریخ را به صورت فارسی از کاربر میگیره، ثبت نمایش تاریخ رو در لیبل هایی که در نظر گرفته شده به صورت اعداد فارسی نمایش میده و کاراکتر فارسی را به صورت نیل ارسال میکنه و در نتیجه عملیات ریاضی روی اونها قابل انجام نیست. وقتی هم که کد نمایش فارسی رو حذف میکنم، بعد از گرفتن تاریخ جلالی از کاربر، تاریخ میلادی رو در لیبل های مربوطه نمایش میده.
برای واضح تر بیان کردن مشکلم عکسش رو ارسال کردم. در عکس اول تاریخ جلالی رو نشون میده که کاربر تاریخ رو انتخاب میکنه. و در عکس دوم فقط کد تاریخ روز رو به صورت نمایش فارسی گذاشتم و برای لیبل های تاریخ ماه و سال، کد فارسی رو ننوشتم. اما همونطور که میبینید اونها رو به میلادی برگردونده.
ممنون میشم راهنماییم کنید.
![screen shot 2018-01-21 at 12 47 43 pm](https://user-images.githubusercontent.com/33260611/35192532-b77cfa76-fea9-11e7-81fc-dc9d4bdd0a6c.png)
![screen shot 2018-01-21 at 12 48 19 pm](https://user-images.githubusercontent.com/33260611/35192537-c35ab14e-fea9-11e7-9696-f6da339ccb4c.png)

`        //Display Format Date
        let formatterDay = DateFormatter()
        formatterDay.dateStyle = .medium
        formatterDay.timeStyle = .none
        // نمایش تاریخ روز به فارسی
        **formatterDay.calendar = Calendar(identifier: Calendar.Identifier.persian)
        formatterDay.locale = Locale(identifier: "fa_IR")**
        
        formatterDay.dateFormat = "dd"
        let dateStringDay = formatterDay.string(from: picker.date)
        startDateDay.text = "\(dateStringDay)"`

**Comment by euwars** [comment]
<div dir="rtl">
یکی از روش‌هایی که میتونید این کار رو انجام بدین اینه که بجای اینکه زبان‌محلی دیت‌فرمتر رو فارسی ست‌کنید، انگلیسی باشه تا راحت بتونید تبدیلش کنید به عدد و ازش استفاده کنید.
و اگر فارسی نشون دادن عدد توی لیبل براتون مهمه، از نامبرفرمتر استفاده کنید تا اعداد انگلیسی رو قبل از نمایش به فارسی تبدیل کنید

با توجه به کد شما، این میتونه راه حل باشه
</div>

```
// CurrentDate
let currentDate = Date()

// Formatter
let dateFormatter = DateFormatter()
dateFormatter.dateStyle = .medium
dateFormatter.timeStyle = .none
dateFormatter.calendar = Calendar(identifier: .persian)
//dateFormatter.locale = Locale(identifier: "fa_IR")
dateFormatter.dateFormat = "dd"


// Set locale to en_US and use number formatter to fa_IR when u are going to display it.
dateFormatter.locale = Locale(identifier: "en_US")
let engStringDay = dateFormatter.string(from: currentDate)
// intDayValue is no longer nil
let engIntDayValue = Int(engStringDay)


//Convert back to persian number whenevern you need it
let numberFormatter = NumberFormatter()
numberFormatter.locale = Locale(identifier: "fa_IR")
// faStringDay is a farsi string representation of your day
let faStringDay = numberFormatter.string(from: NSNumber(value: engIntDayValue!))
```

**Comment by zohanve** [comment]
عاااالی بود. خیلی ممنون
