### ISSUE TITLE
problem!!! in adding library (pod) to my project 

### ISSUE THREAD

**Issue by farnoushshalileh** [euwars/iOSCourse#2]
bebakhshid kheili basic hast ama man nemitonam bad az command path (directory) file am pod ro ham add konam ba hamoon command pod init ? mammnoon misham agar begid moshkel kojast taze directory ro ham cm mizanam ye khat dar mion mige baraie in file vojood nadare in directory 👎

**Comment by farzadrab** [comment]
فقط دستور
pod
را بزنید ببینید کار میکنه

**Comment by farnoushshalileh** [comment]
كدوم ،شايد دارم اشتباه ميكنم اخه زدم نشد

**Comment by euwars** [comment]
اینو دوباره توضیح میدم توی دوره به موقع

**Comment by farnoushshalileh** [comment]
مرسی
