### ISSUE TITLE
string interpolation 

### ISSUE THREAD

**Issue by farnoushshalileh** [euwars/iOSCourse#3]
bebakhshid kheili basic hast ama man nemitonam bad az command path (directory) file am pod ro ham add konam ba hamoon command pod init ? mammnoon misham agar begid moshkel kojast taze directory ro ham cm mizanam ye khat dar mion mige baraie in file vojood nadare in directory 👎

**Comment by farnoushshalileh** [comment]
string interpolation ro mishe tozih bedid farghesh ba optional va non-optional string chiye va kojaha karbord daran ?? merc

**Comment by euwars** [comment]
جلسات اول توضیح میدم اینو توی دوره
